version: '3.8'
services:
  gateway:
    build: gateway
    image: phonebook_gateway_image
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - PHONEBOOK_SERVER_URL=http://server:9090

  server:
    build: server
    image: phonebook_server_image
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/phonebook


  db:
    image: postgres
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=phonebook
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
