version: '3.8'
services:
  phonebook-service:
    build: ./service
    image: phonebook_service_image
    container_name: phonebook-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/phonebook

  db:
    image: postgres
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=phonebook
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
