drop table if exists users;
drop table if exists phones;

CREATE TABLE IF NOT EXISTS phones
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number  VARCHAR(15)                             NOT NULL,
    type    char(1), --тип мобильный\домашний\рабочий
    state   char(1), --состояние активный\неактивный\удаленный
    country char(3),
    CONSTRAINT pk_numbers PRIMARY KEY (id),
    CONSTRAINT uq_user_number UNIQUE (number)
);

CREATE TABLE IF NOT EXISTS users
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(50)                             NOT NULL,
    number INTEGER,
    notes  VARCHAR(5000), -- какие-либо заметки
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT fk_numbers FOREIGN KEY (number) REFERENCES phones (id)
);