drop table if exists phones;
drop table if exists users;

CREATE TABLE IF NOT EXISTS users
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(50)                             NOT NULL,
    notes   VARCHAR(5000), -- какие-либо заметки
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS phones
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    number  VARCHAR(15)                             NOT NULL,
    type    char(1),       --тип мобильный\домашний\рабочий
    state   char(1),       --состояние активный\неактивный\удаленный
    region char(3),
    notes   VARCHAR(5000), -- какие-либо заметки
    CONSTRAINT pk_numbers PRIMARY KEY (id),
    CONSTRAINT fk_phones FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_user_number UNIQUE (number)
);

