CREATE TABLE IF NOT EXISTS phones
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    users_id INTEGER                                 NOT NULL,
    number   VARCHAR(30)                             NOT NULL,
    type     char(1)                                 NOT NULL, --тип мобильный\домашний\рабочий
    state    char(1)                                 NOT NULL, --состояние активный\неактивный\удаленный
    CONSTRAINT pk_numbers PRIMARY KEY (id),
    CONSTRAINT uq_user_number UNIQUE (number),
    CONSTRAINT fk_users FOREIGN KEY (users_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(50)                             NOT NULL,
    number INTEGER,
    notes  VARCHAR(5000), -- какие-либо заметки
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT fk_numbers FOREIGN KEY (number) REFERENCES phones (id)
);